export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const FETCH_SUBJECTS = "FETCH_SUBJECTS";
export const FETCH_VARIABLES = "FETCH_VARIABLES";
export const SELECT_VARIABLE = "SELECT_VARIABLE";
export const SELECT_YEAR = "SELECT_YEAR";
export const UNSELECT_VARIABLE = "UNSELECT_VARIABLE";
export const UNSELECT_YEAR = "UNSELECT_YEAR";
export const CLEANUP = "CLEANUP";

export const FETCH_DATA = "FETCH_DATA";
